//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caloricity of salad: {0}.
        /// </summary>
        public static string AboutCaloricity {
            get {
                return ResourceManager.GetString("AboutCaloricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info about the salad has loaded from {0}.
        /// </summary>
        public static string AboutLoadFile {
            get {
                return ResourceManager.GetString("AboutLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info about the salad has saved in {0}.
        /// </summary>
        public static string AboutSavedFile {
            get {
                return ResourceManager.GetString("AboutSavedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About vegetables in the salad:.
        /// </summary>
        public static string AboutVegetables {
            get {
                return ResourceManager.GetString("AboutVegetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories per {0} g.:.
        /// </summary>
        public static string CaloriesPerUnitWeigth {
            get {
                return ResourceManager.GetString("CaloriesPerUnitWeigth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About vegetables in the salad:.
        /// </summary>
        public static string CheckToString {
            get {
                return ResourceManager.GetString("CheckToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color is undefined..
        /// </summary>
        public static string ColorIsUndefined {
            get {
                return ResourceManager.GetString("ColorIsUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ColorOfVegetable {
            get {
                return ResourceManager.GetString("ColorOfVegetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You input incorrect max calorie of vegetable per unit of weigth. 
        ///Max calorie of vegetable per unit of weigth must be integer..
        /// </summary>
        public static string ErrorRange {
            get {
                return ResourceManager.GetString("ErrorRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Export Menu:
        ///[1] -- From txt&apos;s file
        ///[2] -- From bin&apos;s file
        ///
        ///[Q] -- Exit
        ///    .
        /// </summary>
        public static string ExportMenu {
            get {
                return ResourceManager.GetString("ExportMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info about the salad has not loaded. File {0} has been not found or contains incorrect data..
        /// </summary>
        public static string FileNotLoaded {
            get {
                return ResourceManager.GetString("FileNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info about the salad has not saved. File {0} has not created..
        /// </summary>
        public static string FileNotSaved {
            get {
                return ResourceManager.GetString("FileNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Import Menu:
        ///[1] -- From txt&apos;s file
        ///[2] -- From bin&apos;s file
        ///
        ///[Q] -- Exit
        ///    .
        /// </summary>
        public static string ImportMenu {
            get {
                return ResourceManager.GetString("ImportMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Main menu:
        ///[1] -- About vegetables in the salad
        ///[2] -- Caloricity of salad
        ///[3] -- Sort vegetables by color
        ///[4] -- Search vegetables by calories per unit of weigth
        ///[5] -- Search vegetable by Id
        ///[6] -- Storage
        ///
        ///[Q] -- Exit
        ///    .
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetable:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is undefined..
        /// </summary>
        public static string NameIsUndefined {
            get {
                return ResourceManager.GetString("NameIsUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetable.
        /// </summary>
        public static string NameOfVegetable {
            get {
                return ResourceManager.GetString("NameOfVegetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vegetable doesn&apos;t exist with Id = {0}..
        /// </summary>
        public static string NotExistId {
            get {
                return ResourceManager.GetString("NotExistId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salad contains only one vegetable:
        ///{0}..
        /// </summary>
        public static string OneVegetable {
            get {
                return ResourceManager.GetString("OneVegetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press any key to exit in the main menu..
        /// </summary>
        public static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could you please specify id of vegetable?.
        /// </summary>
        public static string QuestionId {
            get {
                return ResourceManager.GetString("QuestionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could you please specify max calorie of vegetable per unit of weigth?.
        /// </summary>
        public static string QuestionRange {
            get {
                return ResourceManager.GetString("QuestionRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of search is empty..
        /// </summary>
        public static string ResultEmpty {
            get {
                return ResourceManager.GetString("ResultEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salad doesn&apos;t have any vegetable..
        /// </summary>
        public static string SaladIsEmpty {
            get {
                return ResourceManager.GetString("SaladIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salad contains same vegetable..
        /// </summary>
        public static string SameVegetable {
            get {
                return ResourceManager.GetString("SameVegetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string Sharp {
            get {
                return ResourceManager.GetString("Sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string SpliterOfData {
            get {
                return ResourceManager.GetString("SpliterOfData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string SpliterOfTitle {
            get {
                return ResourceManager.GetString("SpliterOfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Storage Menu:
        ///[1] -- Export
        ///[2] -- Import
        ///
        ///[Q] -- Exit
        ///    .
        /// </summary>
        public static string StorageMenu {
            get {
                return ResourceManager.GetString("StorageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chef.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total calories:.
        /// </summary>
        public static string TotalCalories {
            get {
                return ResourceManager.GetString("TotalCalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavedFile.txt.
        /// </summary>
        public static string TxtFile {
            get {
                return ResourceManager.GetString("TxtFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Of Weigth, g:.
        /// </summary>
        public static string UnitOfWeigth {
            get {
                return ResourceManager.GetString("UnitOfWeigth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some object isn&apos;t vegetable..
        /// </summary>
        public static string VegetableIsNull {
            get {
                return ResourceManager.GetString("VegetableIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight, g:.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
